# Generated by Django 5.0.6 on 2025-08-23 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='plateNumber',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(db_index=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='gate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='status',
            field=models.CharField(choices=[('open', 'OPEN'), ('closed', 'CLOSED')], db_index=True, default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='app.vehicle'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID'), ('failed', 'FAILED'), ('refunded', 'REFUNDED')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('revoked', 'REVOKED'), ('expired', 'EXPIRED')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='value',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
