# Generated by Django 5.0.6 on 2025-08-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_vehicle_platenumber_vehicle_plate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='last_plate',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
