# Generated by Django 5.0.6 on 2025-08-29 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_qrcode_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('car', 'CAR'), ('motorbike', 'MOTORBIKE')], max_length=16)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('estimated_fee', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('booked', 'BOOKED'), ('active', 'ACTIVE'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('expired', 'EXPIRED'), ('overstayed', 'OVERSTAYED')], default='booked', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='qrcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='app.qrcode'),
        ),
        migrations.AlterField(
            model_name='platereading',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='app.parkingsession'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('owner', 'plate_number'), name='uq_owner_plate'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='app.reservation'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr', to='app.reservation'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['user', 'status'], name='app_parking_user_id_5ab429_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['entry_time'], name='app_parking_entry_t_51f09b_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['status', 'expired_at'], name='app_qrcode_status_54da8d_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'start_time'], name='app_reserva_user_id_309c02_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='app_reserva_status_70cab5_idx'),
        ),
    ]
